image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build Cooja and Start VNC
    command: |
      git submodule update --init --recursive
      cd tools/cooja
      ant run &
      tail -f /dev/null

ports:
  - port: 5901
    onOpen: open-preview
    visibility: public


